### ISSUE TITLE
variable data length

### ISSUE THREAD

**Issue by tpoint75** [athombv/node-linux-device#1]
I'm trying to read strings with variable length (they end with '\n' for instance):

var xlog = new Buffer(0);
var xdevice = new DeviceHandle('/dev/xconsole', true, 1, function(err, data) {
	xlog = Buffer.concat([xlog, data]);
	while(xlog.toString().search('\n')>=0){
		console.log(xlog.slice(0,xlog.toString().search('\n')).toString())
		xlog = xlog.slice(xlog.toString().search('\n')+1);
	}
});

The code is working and I get the text but its real slow. The problem is that every sign will call an event (callback function)..

Is there a way to get it faster or what do I do wrong?

**Comment by jeroenvollenbrock** [comment]
@tpoint75 version 1.0.5 adds a minimal size (currently undocumented).

```
new DeviceHandle(string path, boolean enableWrite, positive number objectSize, [positive number minimalObjectSize,] function callback)
```

**Comment by tpoint75** [comment]
This works great! Thank you very much! Issue solved!
