### ISSUE TITLE
emulate a linux device

### ISSUE THREAD

**Issue by pacmac** [athombv/node-linux-device#21]
Sorrie, this is more of a question than an issue.

Can this be used to emulate a linux device, say for example I created a device '/dev/nodetty', am I able to connect to this device using a linux serial console and be able to transmit and receive to nodejs as though it was a linux serial device ?

Thanks

**Comment by jeroenvollenbrock** [comment]
This should indeed be possible, you can either use a named pipe ([mkfifo](https://linux.die.net/man/1/mkfifo)) for unidirectional communication (either read/write). But i think you might be looking for a [pseudo terminal interface](http://man7.org/linux/man-pages/man7/pty.7.html). (bi-directional)
